<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?php echo _('All Pages'); ?></h3>
            </div>
            <div class="box-body">
                <table id="orders-table" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th class=""><?php echo _('Page Name'); ?></th>
                            <th class="hidden-sm hidden-xs"><?php echo _('Created'); ?></th>
                            <th class="hidden-sm hidden-xs"><?php echo _('Modified'); ?></th>
                            <th class="hidden-sm hidden-xs"><?php echo _('Status'); ?></th>
                            <th class="text-right"><?php echo _('Actions'); ?></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                    <tfoot>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th><input type="text" id="column6_search" class="form-control hidden-sm hidden-xs" placeholder="<?php echo _('Search'); ?>" /></th>
                            <th></th>
                        </tr>
                        <tr>
                            <th>ID</th>
                            <th class=""><?php echo _('Page Name'); ?></th>
                            <th class="hidden-sm hidden-xs"><?php echo _('Created'); ?></th>
                            <th class="hidden-sm hidden-xs"><?php echo _('Modified'); ?></th>
                            <th class="hidden-sm hidden-xs"><?php echo _('Status'); ?></th>
                            <th class="text-right"><?php echo _('Actions'); ?></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
