<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?php echo $t->_('settings'); ?></h3>
            </div>
            
            <form role="form" method="post">
                <input type="hidden" name="<?php echo $tokenKey; ?>" value="<?php echo $token; ?>">
                <!-- /.box-header -->
                <div class="box-body">
                    <?php $this->flashSession->output(); ?>

                    <div class="form-group">
                        <label for="state"><?php echo $t->_('payment'); ?></label>
                        <?php echo $form->render('payment'); ?>
                    </div>
                    
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
                <!-- /.box-body -->
            </form>
        </div>
        <!-- /.box -->
    </div>
    
</div>
