        <aside class="main-sidebar">
            <section class="sidebar">
                <div class="user-panel">
                    <div class="pull-left image">
                        <!-- img src="<?php echo $this->tag->gravatar($identity->email, 160); ?>" class="img-circle" width="160" height="160" alt="" -->
                        <img src="/assets/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p><?php echo $identity->getFullname(); ?></p>
                        <!-- a href="#"><i class="fa fa-circle text-success"></i> Online</a -->
                    </div>
                </div>
                
                <!-- form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </form -->
                
                <ul class="sidebar-menu">
                    <li class="header"><?php echo $t->_('navigation'); ?></li>
                    <li class="">
                        <a href="/admin/pages">
                            <i class="fa fa-file"></i>
                            <span><?php echo _('Pages'); ?></span>
                        </a>
                    </li>
                    <li class="">
                        <a href="/admin/users">
                            <i class="fa fa-users"></i>
                            <span><?php echo _('Users'); ?></span>
                        </a>
                    </li>
                    <li class="">
                        <a href="/admin/settings">
                            <i class="fa fa-cog"></i>
                            <span><?php echo _('Settings'); ?></span>
                        </a>
                    </li>
                </ul>
            </section>
        </aside>

