
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- img src="<?php echo $this->tag->gravatar($identity->email, 160); ?>" class="user-image" alt="User Image" -->
                                <img src="/assets/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs"><?php echo $identity->getFullname(); ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <!-- img src="<?php echo $this->tag->gravatar($identity->email, 160); ?>" class="img-circle" alt="User Image" -->
                                    <img src="/assets/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                                    <p>
                                        <?php echo $identity->getFullname(); ?> - <?php // echo $identity->getGroup()->name; ?>
                                        <small><?php // echo $identity->dateCreated; ?></small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <!-- li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Followers</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Sales</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Friends</a>
                                        </div>
                                    </div>
                                </li -->
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat"><?php echo $t->_('profile'); ?></a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="<?php echo $this->tag->u('admin', 'auth', 'logout'); ?>" class="btn btn-default btn-flat"><?php echo $t->_('logout'); ?></a>
                                    </div>
                                </li>
                            </ul>
                        </li>

