        <div class="container products">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger" role="alert" style="display:none;"><ul class="list-unstyled"></ul></div>
                </div>
            </div>
            
            <!-- div class="row">
                <div class="col-md-12">
                    <h1>Calming Сube <span>(mixed colors)</span></h1>
                </div>
            </div -->

            <div class="row">
                <div class="col-md-4">
                    <div class="item">
                        <div class="price-per-unit"><?php echo $t->_('price.per.unit'); ?></div>
                        <div class="img cube-1-device-pack"></div>
                        <div class="title"><?php echo $products[1]['name']; ?></div>
                        <div class="price">$<?php echo $products[1]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="1">SELECT</a></div>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="item">
                        <div class="price-per-unit"><?php echo $t->_('price.per.unit'); ?></div>
                        <div class="img spinner-1-device-pack"></div>
                        <div class="title"><?php echo $products[4]['name']; ?></div>
                        <div class="price">$<?php echo $products[4]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="4">SELECT</a></div>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="item">
                        <div class="price-per-unit"><?php echo $t->_('price.two.units'); ?></div>
                        <div class="img mix-1-1"></div>
                        <div class="title"><?php echo $products[7]['name']; ?></div>
                        <div class="price"><span>$59.80</span> $<?php echo $products[7]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="7">SELECT</a></div>
                    </div>
                </div>
            </div>
            
            <!-- div class="row">
                <div class="col-md-12">
                    <h1>Anti-Stress Spinner <span>(mixed colors)</span></h1>
                </div>
            </div -->
            
            <div class="row">
                <div class="col-md-4">
                    <div class="item">
                        <div class="price-per-unit">$12.00 <?php echo $t->_('price.per.unit.40'); ?></div>
                        <div class="img cube-buy-3-get-2-free"></div>
                        <div class="title"><?php echo $t->_('pack.3.2'); ?></div>
                        <div class="price"><span>$149.70</span> $<?php echo $products[2]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="2">SELECT</a></div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="item">
                        <div class="price-per-unit">$12.00 <?php echo $t->_('price.per.unit.40'); ?></div>
                        <div class="img spinner-buy-3-get-2-free"></div>
                        <div class="title"><?php echo $t->_('pack.3.2'); ?></div>
                        <div class="price"><span>$149.70</span> $<?php echo $products[5]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="5">SELECT</a></div>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="item">
                        <div class="price-per-unit">$8.00 <?php echo $t->_('price.per.unit.60'); ?></div>
                        <div class="img mix-5-5"></div>
                        <div class="title"><?php echo $t->_('pack.4.6'); ?> (5 + 5)</div>
                        <div class="price"><span>$299</span> $<?php echo $products[8]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="8">SELECT</a></div>
                    </div>
                </div>
            </div>

            <!-- div class="row">
                <div class="col-md-12">
                    <h1>Cube + Spinner <span>(mixed colors)</span></h1>
                </div>
            </div -->

            <div class="row">
                <div class="col-md-4">
                    <div class="item">
                        <div class="ribbon"><span>Best Deal</span></div>
                        <div class="price-per-unit">$8.00 <?php echo $t->_('price.per.unit.60'); ?></div>
                        <div class="img cube-buy-4-get-6-free"></div>
                        <div class="title"><?php echo $t->_('pack.4.6'); ?></div>
                        <div class="price"><span>$299</span> $<?php echo $products[3]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="3">SELECT</a></div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="item">
                        <div class="ribbon"><span>Best Deal</span></div>
                        <div class="price-per-unit">$8.00 <?php echo $t->_('price.per.unit.60'); ?></div>
                        <div class="img spinner-buy-4-get-6-free"></div>
                        <div class="title"><?php echo $t->_('pack.4.6'); ?></div>
                        <div class="price"><span>$299</span> $<?php echo $products[6]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="6">SELECT</a></div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="item">
                        <div class="ribbon"><span>Best Deal</span></div>
                        <div class="price-per-unit">$7.00 <?php echo $t->_('price.per.unit.70'); ?></div>
                        <div class="img mix-8-8"></div>
                        <div class="title"><?php echo $t->_('pack.6.10'); ?> (8 + 8)</div>
                        <div class="price"><span>$479</span> $<?php echo $products[9]['price']; ?></div>
                        <div class="text-center"><a href="#" class="btn btn-fidget border" data-product="9">SELECT</a></div>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger" role="alert" style="display:none;"><ul class="list-unstyled"></ul></div>
                </div>
            </div>
        </div>

<script type="text/javascript">
    window.step = 1;
    window.lang = '<?php echo $lang; ?>';
</script>
